### ISSUE TITLE
Invalid bitfield flag or number

### ISSUE THREAD

**Issue by AsianHyun** [elbkr/music-bot#121]
```[Interaction] An error occured while trying to trigger slashCommands
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: MANAGE_GUILD.

RangeError [BitFieldInvalid]: Invalid bitfield flag or number: MANAGE_GUILD.
    at Function.resolve (/home/ubuntu/discord-music/node_modules/discord.js/src/util/BitField.js:168:11)
    at PermissionsBitField.has (/home/ubuntu/discord-music/node_modules/discord.js/src/util/BitField.js:60:28)
    at PermissionsBitField.has (/home/ubuntu/discord-music/node_modules/discord.js/src/util/PermissionsBitField.js:92:82)
    at Skip.exec (/home/ubuntu/discord-music/src/commands/music/skip.js:48:66)
    at SlashCommands.exec (/home/ubuntu/discord-music/src/events/interactions/slashCommands.js:15:23)
    at Bot.<anonymous> (/home/ubuntu/discord-music/src/struct/Bot.js:144:80)
    at Bot.emit (node:events:513:28)
    at InteractionCreate.exec (/home/ubuntu/discord-music/src/events/interactions/interactionCreate.js:15:93)    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by elbkr** [comment]
Hi, in skip.js line 48 you have to change permissions.has("MANAGE_GUILD") to the new form. Give me a min

**Comment by elbkr** [comment]
put this instead of "MANAGE_GUILD" `PermissionsBitField.Flags.ManageGuild` and tell me if it works ^^
And at the top of the file put `const {PermissionsBitField} = require("discord.js");`

**Comment by AsianHyun** [comment]
It worked ! thanks :3

**Comment by WillKirkmanM** [comment]
Hey

As of commit https://github.com/elbkr/music-bot/commit/24a88b4e2f886a17219136dee451705bb5322760, in respect to the new import / export syntax of EcmaScript 6 (ES6). The new syntax would be:

```javascript
import { PermissionsBitField } from "discord.js";
```
You do not need to touch the `PermissionsBitField.Flags.ManageGuild` in the intents section.

Kind Regards,
Will
