### ISSUE TITLE
Couldn't join the voice channel

### ISSUE THREAD

**Issue by dxkyy** [elbkr/music-bot#98]
When I do any command, I get this error: 
```
[17-08-2022 18:25:58]: [Player] Couldn't join the voice channel
TypeError: channel.isVoice is not a function

TypeError: channel.isVoice is not a function
    at Queue.join (C:\Users\adrian\Desktop\dev\discord\music-bot\node_modules\discord-music-player\dist\managers\Queue.js:91:22)
    at Bot.play (C:\Users\adrian\Desktop\dev\discord\music-bot\src\player\functions\play.js:25:17)
    at Play.exec (C:\Users\adrian\Desktop\dev\discord\music-bot\src\commands\music\play.js:88:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SlashCommands.exec (C:\Users\adrian\Desktop\dev\discord\music-bot\src\events\interactions\slashCommands.js:15:13)
C:\Users\adrian\Desktop\dev\discord\music-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:101
    if (this.deferred || this.replied) throw new Error(ErrorCodes.InteractionAlreadyReplied);
                                             ^

Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (C:\Users\adrian\Desktop\dev\discord\music-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:101:46)
    at Bot.play (C:\Users\adrian\Desktop\dev\discord\music-bot\src\player\functions\play.js:42:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SlashCommands.exec (C:\Users\adrian\Desktop\dev\discord\music-bot\src\events\interactions\slashCommands.js:15:13) {
  [Symbol(code)]: 90
}
```
How can I fix this?

**Comment by elbkr** [comment]
I just noticed the error in the code. Thanks for letting me know ^^ I’ll upfate the repo todsy

**Comment by elbkr** [comment]
I was about to fix it but I saw that the problem is in your code. You updated discord.js without getting the last version of this repository, which already has all the changes correctly made
