### ISSUE TITLE
Couldn't join the voice channel

### ISSUE THREAD

**Issue by dxkyy** [elbkr/music-bot#99]
I was about to fix it but I saw that the problem is in your code. You updated discord.js without getting the last version of this repository, which already has all the changes correctly made

_Originally posted by @elbkr in https://github.com/elbkr/music-bot/issues/98#issuecomment-1218561093_

I cloned the repository again just now and typed in "npm i", but I still get the same error whenever I try to use any command?
```
TypeError: channel.isVoice is not a function

TypeError: channel.isVoice is not a function
    at Queue.join (C:\Users\adrian\Desktop\dev\music-bot\node_modules\discord-music-player\dist\managers\Queue.js:91:22)
    at Bot.play (C:\Users\adrian\Desktop\dev\music-bot\src\player\functions\play.js:25:17)
    at Play.exec (C:\Users\adrian\Desktop\dev\music-bot\src\commands\music\play.js:88:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SlashCommands.exec (C:\Users\adrian\Desktop\dev\music-bot\src\events\interactions\slashCommands.js:15:13)
C:\Users\adrian\Desktop\dev\music-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:101
    if (this.deferred || this.replied) throw new Error(ErrorCodes.InteractionAlreadyReplied);
                                             ^

Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (C:\Users\adrian\Desktop\dev\music-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:101:46)
    at Bot.play (C:\Users\adrian\Desktop\dev\music-bot\src\player\functions\play.js:42:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SlashCommands.exec (C:\Users\adrian\Desktop\dev\music-bot\src\events\interactions\slashCommands.js:15:13) {
  [Symbol(code)]: 90
}
```

**Comment by elbkr** [comment]
Can you send here what version of discord-music-player you have installed?

**Comment by dxkyy** [comment]
> Can you send here what version of discord-music-player you have installed?

In the package.json of discord-music-player it says ` "version": "8.3.2"`.

**Comment by dxkyy** [comment]
Ahh, I updated discord-music-player to the newest version, and it works now, ty!
